### ISSUE TITLE
Error with CI Workflow

### ISSUE THREAD

**Issue by mrmrinal** [nus-cs2103-AY2122S1/forum#200]
I'm currently having a bit of difficulty setting up the CI workflow for my iP. I'm currently getting the following error, and am unsure as to how to to go about resolving it. I'm currently using a windows system and have removed the macOS and ubuntu options for the yml. As for my ubuntu test, I'm getting an error with my Build and check with gradle portion.

![image](https://user-images.githubusercontent.com/77235299/132251746-28200217-8189-4c0e-a25b-d357d906a9f7.png)

Here is my gradle.yml file 

```yml
name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check

      - name: Perform IO redirection test (Windows)
        if: always() && runner.os == 'Windows'
        working-directory:  ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat
```

**Comment by AllardQuek** [comment]
Maybe try removing the last IO segment? 

![image](https://user-images.githubusercontent.com/40263305/132273148-7d42f62b-5c4f-4eef-953e-f4075a088299.png)

**Comment by marcuspeh** [comment]
I removed all these from my gradle.yml
```
      - name: Perform IO redirection test (*NIX)
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (MacOS)
        if: always() && runner.os == 'macOS'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (Windows)
        if: always() && runner.os == 'Windows'
        working-directory:  ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat
```

**Comment by bharathcs** [comment]
Btw your Github action currently calls for the task to be run on Windows, Linux and Mac platforms, and you have to wait for all the tasks to be repeated thrice. If you are just running `gradlew check` for checkstyle and you aren't testing anything that could be platform dependent, you can do just run the action on just linux and save your time. 

Something like this:

```
jobs:
  build:
    runs-on: ubuntu-latest
```

Replacing these lines:
```
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
```
