### ISSUE TITLE
full-template branch: gradle.yml is outdated

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY2122S1/forum#458]
Outdated as compared to AB3 equivalent.
In particular,
```
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx
```
